### ISSUE TITLE
Seed data should be optional

### ISSUE THREAD

**Issue by wilbertom** [propublica/cookcountyjail2#16]
Since I don't have any of the old daily inmate summaries, I can't run the scraper locally. This should be optional for the first run.

```
2017-06-10 14:53:47 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2017-06-10 14:53:47 [scrapy.core.engine] INFO: Spider opened
2017-06-10 14:53:47 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2017-06-10 14:53:47 [scrapy.extensions.telnet] DEBUG: Telnet console listening on 127.0.0.1:6023
2017-06-10 14:53:47 [scrapy.core.engine] ERROR: Error while obtaining start requests
Traceback (most recent call last):
  File "/home/wil/.virtualenvs/ccj-cookcountyjail2/lib/python3.6/site-packages/scrapy/core/engine.py", line 127, in _next_request
    request = next(slot.start_requests)
  File "/home/wil/code/ccj/cookcountyjail2/jailscraper/spiders/inmate_spider.py", line 32, in start_requests
    for url in self._generate_urls():
  File "/home/wil/code/ccj/cookcountyjail2/jailscraper/spiders/inmate_spider.py", line 59, in _generate_urls
    last_file = keys[-1].get()
IndexError: list index out of range
```

**Comment by eads** [comment]
@wilbertom and I talked about this on the phone... 

Current plan is:

* Still rely on s3/remote storage of these files.
* But fall back to a local version if those cannot be accessed.

**Comment by eads** [comment]
Assigned myself.

**Comment by eads** [comment]
hmm this should have been closed
